---
title: "Analysis of interest rate in Brazil"
Author: "Pedro Philippi Araujo"
format: 
  html: 
    embed: true
execute:
  environment: python3
jupyter: python3
kernel: python3
---



## Introduction

The purpose of this notebook is to acquire and understand data from the Banco Central do Brasil (Brazil Central Bank) in order to create a model prediction for interest rates.


## Data Acquisition

We are going to download through url request the following series of data:

433 - Índice nacional de preços ao consumidor-amplo (IPCA) -- National index of ample-consumer prices: Measures inflation.

11753 - Índice da taxa de câmbio real (IPCA) -- Exchange rate index to dollars : Measures how much a Brazilian Real (R$) is valued in comparison to a dollar.

24363 - Índice de Atividade Econômica do Banco Central - IBC-Br  -- Central Bank economic activity indes: Similar to GPD, but on a monthly basis.

 24369 - Taxa de desocupação - PNADC -- unemployment rate 


```{python}


import os
import urllib.request


parameters_url = "https://www3.bcb.gov.br/sgspub/consultarvalores/consultarValoresSeries.do?method=downLoad"

selic_url1 = "https://api.bcb.gov.br/dados/serie/bcdata.sgs.11/dados?formato=csv&dataInicial=01/03/2012&dataFinal=01/03/2022"

selic_url2 = "https://api.bcb.gov.br/dados/serie/bcdata.sgs.11/dados?formato=csv&dataInicial=26/02/2022&dataFinal=25/05/2025"

archive_path_params = "../data/sgsdata.csv"

archive_path_selic1 = "../data/selicdatapt1.csv"

archive_path_selic2 = "../data/selicdatapt2.csv"

if not (os.path.exists(archive_path_params)):
    urllib.request.urlretrieve(parameters_url, archive_path)
if not (os.path.exists(archive_path_selic1)):
    urllib.request.urlretrieve(selic_url1, archive_path_selic1)
if not (os.path.exists(archive_path_selic2)):
    urllib.request.urlretrieve(selic_url2, archive_path_selic2)


print("Data Downloaded")

```

```{python}
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


```


## Data Transformation of Parameters Dataframe

```{python}

df = pd.read_csv(archive_path_params,sep=";", encoding='latin1')


df = df.rename(columns={'Data':'Date','433 - Índice nacional de preços ao consumidor-amplo (IPCA) - Var. % mensal': 'IPCA', '11753 - Índice da taxa de câmbio real (IPCA) - Jun/1994=100 - Dólar americano - Índice':'Exchange Rate', '20714 - Taxa média de juros das operações de crédito - Total - % a.a.': 'Interest Rate', '24363 - Índice de Atividade Econômica do Banco Central - IBC-Br - Índice': 'GDP', '24369 - Taxa de desocupação - PNADC - %': 'Unemployement Rate'})


df = df.set_index('Date')

df = df.drop(df[df["Exchange Rate"] == '-'].index)
df = df.drop(df[df["Interest Rate"] == '-'].index)
df = df.drop(df[df["Unemployement Rate"] == '-'].index)
df = df.head(len(df)-1)

df = df.replace(r',','.', regex=True)

df['IPCA'] = df['IPCA'].astype(float)
df['Exchange Rate'] = df['Exchange Rate'].astype(float)
df['Interest Rate'] = df['Interest Rate'].astype(float)
df['GDP'] = df['GDP'].astype(float)
df['Unemployement Rate'] = df['Unemployement Rate'].astype(float)



df.index = pd.to_datetime(df.index)

df_daily = df.resample("D").ffill()


df_daily.head


```


## Data Understanding

```{python}
sns.lineplot(data=df[0:40], x='Date', y='IPCA')
plt.title('Line Plot of Date vs IPCA')
plt.xlabel('Date')
plt.xticks(rotation=90)
plt.ylabel('IPCA')
plt.show()
plt.close()


sns.lineplot(data=df[0:40], x='Date', y='Exchange Rate')
plt.title('Line Plot of Date vs Exchange Rate')
plt.xlabel('Date')
plt.xticks(rotation=90)
plt.ylabel('Exchange Rate')
plt.show()
plt.close()

sns.lineplot(data=df[0:40], x='Date', y='Interest Rate')
plt.title('Line Plot of Date vs Interest Rate')
plt.xlabel('Date')
plt.xticks(rotation=90)
plt.ylabel('Interest Rate')
plt.show()
plt.close()


sns.lineplot(data=df[0:40], x='Date', y='GDP')
plt.title('Line Plot of Date vs GDP')
plt.xlabel('Date')
plt.xticks(rotation=90)
plt.ylabel('GDP')
plt.show()
plt.close()

sns.lineplot(data=df[0:40], x='Date', y='Unemployement Rate')
plt.title('Line Plot of Date vs Unemployement Rate')
plt.xlabel('Date')
plt.xticks(rotation=90)
plt.ylabel('Unemployement Rates')
plt.show()
plt.close()

```



# Data Transformation of SELIC Rate


```{python}

df_selic = pd.read_csv(archive_path_selic1, sep=";", encoding='latin1')

df_selic2 = pd.read_csv(archive_path_selic2, sep=';', encoding='latin1')



df_selic = pd.concat([df_selic, df_selic2], ignore_index=True)


df_selic = df_selic.rename(columns={'data':'Date', 'valor':'SELIC'})

df_selic["Date"] = pd.to_datetime(df_selic["Date"],format="%d/%m/%Y")

df_selic = df_selic.set_index('Date')

df_selic = df_selic.replace(r',','.', regex=True)

df_selic['SELIC'] = df_selic['SELIC'].astype(float)


df_selic['SELIC+30'] = df_selic["SELIC"].shift(-30)

df_selic = df_selic.dropna()

df_selic['Variation'] = df_selic["SELIC+30"] - df_selic["SELIC"]

df_selic.head


```



# Join of the two dataframes

```{python}

df_final = df_daily.join(df_selic)

df_final = df_final.dropna()

df_final.head

#Save to CSV
df_final.to_csv('../data/databasefinal.csv')

```